server:
  port: 8081

keycloak:
  auth-server-url: http://quant_keycloak:8080/
  realm: quant
  resource: quant-api
  credentials:
    secret: api-secret-123
  bearer-only: true
  ssl-required: none
  use-resource-role-mappings: true

spring:
  application:
    name: quant-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://quant_keycloak:8080/realms/quant

  datasource:
    url: jdbc:mysql://192.168.1.26:13306/workflow?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri: mongodb://root:root@192.168.1.26:27018/quantdb?authSource=admin
      database: quantdb