name: Build and Push quant_api Image and Create PR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short Git commit hash
        id: vars
        run: echo "COMMIT_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            xiz001/quant_api:latest
            xiz001/quant_api:${{ env.COMMIT_TAG }}

      - name: Create Pull Request in quant_docker
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.MAIN_REPO_PAT }}
          repository: xiz001/quant_docker
          branch: update-api-image-${{ env.COMMIT_TAG }}
          title: "Update quant_api image to ${{ env.COMMIT_TAG }}"
          commit-message: "Update quant_api image tag to ${{ env.COMMIT_TAG }}"
          body: |
            This PR updates **quant_api** image tag to `${{ env.COMMIT_TAG }}`.
          add-paths: docker-compose.yml
          base: main
          update-branch: true

      - name: Modify docker-compose.yml in quant_docker
        run: |
          git clone https://xiz001:${{ secrets.MAIN_REPO_PAT }}@github.com/xiz001/quant_docker.git
          cd quant_docker
          sed -i "s|xiz001/quant_api:.*|xiz001/quant_api:${{ env.COMMIT_TAG }}|g" docker-compose.yml
          git add docker-compose.yml
          git commit -m "Update quant_api image tag to ${{ env.COMMIT_TAG }}"
          git push origin update-api-image-${{ env.COMMIT_TAG }}